version: "3.8"

services:

  golang:
    container_name: golang
    volumes:
     - ./src:/go/src
    working_dir: /go/src
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    env_file: .env
